- name: Install basic software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk*
    - httpd

- name: Restart tomcat
  service:
    name: httpd
    state: restarted
